### ISSUE TITLE
howto?

### ISSUE THREAD

**Issue by vespino** [cybercinch/certbot-dns-directadmin#14]
I would like to try this plugin (is that what it's called), but I have not idea where to begin. I downloaded the tar.gz file and extracted it to /opt/certbot-dns-directadmin but then what?

**Comment by guisea** [comment]
Hi,    
  

  
So you need to install certbot and also this plugin locally.    No need to download the src it is published to Pypi.    
  

  
To just try it out you can use the premade docker image.    See:   https://hub.docker.com/r/cybercinch/certbot-dns-directadmin
  

  
Also the docs for the plugin will step through creation of credentials file and the command line parameters.    
  

  
 https://certbot-dns-directadmin.readthedocs.io/en/stable/index.html
    

  
  
  
  
  
  
  

  
  
>

**Comment by vespino** [comment]
So the idea behind this project/plugin is not integrating it into an existing project, but running it on the side only to create the certificates and then move them to the project?

**Comment by guisea** [comment]
Correct,    it is a plugin for a standalone tool named certbot.    
  
  
  
  
  
  
  

  
  
>

**Comment by vespino** [comment]
Cheers. And what about this remark? https://github.com/cybercinch/certbot-dns-directadmin/issues/11

**Comment by guisea** [comment]
Not able to replicate.  I have provisioned with latest.  And this driver/plugin is integrated with SWAG a reverse proxy which provides SSL via certbot and this plugin.

**Comment by vespino** [comment]
Alright, I’ll give this a try, if it works it would help me out a lot.

**Comment by vespino** [comment]
I created a docker-compose.yml like this...

```
services:
  certbot-dns-directadmin:
    build: .
    image: certbot-dns-directadmin
    container_name: certbot-dns-directadmin
    ports:
      - 8080:80
      - 8081:443
```

...and placed the Dockerfile in the same directory:

```
FROM certbot/certbot:latest
RUN pip install certbot-dns-directadmin
```

When running sudo docker-compose up -d the container spins up, shows the following logs and stops:

```
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
```

**Comment by vespino** [comment]
Same when I use the following docker-compose.yml:

```
services:
  certbot-dns-directadmin:
    image: cybercinch/certbot-dns-directadmin:latest
    container_name: certbot-dns-directadmin
    ports:
      - 8080:80
      - 8081:443
```
